
version: '3.8'
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Mynewdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
      
      
  springboot:
    image: myapp:latest
    container_name: my_app121
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/Mynewdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Apple.nextiva@123
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 9090
    volumes:
      - springboot-data:/Users/shruti.jain/Desktop/shrutiapp
    depends_on:
      - mysql
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
    
volumes:
  mysql-data:
  springboot-data:
